package com.excilys.persistence;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Classe permettant de récupérer la connexion à la base de données.
 *
 * @author jguyot2
 *
 */
public final class DBConnection {
    /** */
    private static final String DB_NAME = "computer-database-db";
    /** Instance unique de la connexion à la base. */
    private static DBConnection dbConnInstance;

    /** */
    private static final String DRIVER_NAME = "com.mysql.cj.jdbc.Driver";
    /** */
    private static final Logger LOG =
        LoggerFactory.getLogger(ComputerUpdater.class);
    /** */
    private static final String PASSWORD = "qwerty1234";

    /** */
    private static final String TEST_DB_NAME = "computer-database-db-test";
    /** */
    private static boolean testMode = false;

    /** */
    private static final String URL_DB = "jdbc:mysql://localhost:3306/";

    /** */
    private static final String USERNAME = "admincdb";

    /**
     * @return l'instance courante de la connexion à la base.
     **/
    public static DBConnection getConnection() {
        if (dbConnInstance == null || dbConnInstance.isClosed()) {
            dbConnInstance = new DBConnection();
        }
        return dbConnInstance;
    }

    /** */
    private Connection conn;

    /** */
    private final String dbName;

    private DBConnection() {
        LOG.info("Instanciation");
        if (testMode) {
            this.dbName = TEST_DB_NAME;
        } else {
            this.dbName = DB_NAME;
        }
        init();
    }

    /** Fermeture de la connexion.
     */
    public void close() throws SQLException {
        if (this.conn == null) {
            return;
        }
        this.conn.close();
        this.conn = null;
    }

    /**
     * @return un statement pour faire des requêtes.
     */
    public Statement createStatement() throws SQLException {
        return this.conn.createStatement();
    }

    /**
     * Préparation d'un Statement sur une requête prédéfinie.
     * @param sqlPreparedRequest la requête préparée, en
     * remplaçant les paramètres par des?
     * @return une instance de PerparedStatement associée à la requête en
     * paramètre
     */
    public PreparedStatement prepareStatement(final String sqlPreparedRequest)
        throws SQLException {

        return this.conn.prepareStatement(sqlPreparedRequest);
    }

    /**
     *
     * @param sqlPreparedRequest La chaîne de caractères correspondant à une
     * requête préparée.
     * @param autoGeneratedKeys un flag indiquant si les clefs
     * retournées lors de la requêtes doivent être générées
     * @return Un preparedStatement associé aux paramètres
     * @throws SQLException
     */
    public PreparedStatement prepareStatement(
        final String sqlPreparedRequest,
        final int autoGeneratedKeys) throws SQLException {
        return this.conn.prepareStatement(sqlPreparedRequest, autoGeneratedKeys);
    }

    private void init() {
        LOG.info("import du driver JDBC");
        try {

            Class.forName(DRIVER_NAME).newInstance();
            this.conn = DriverManager.getConnection(
                URL_DB + this.dbName + "?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris",
                USERNAME,
                PASSWORD);
        } catch (InstantiationException e1) {
            e1.printStackTrace();
            LOG.error("init : " + e1.getMessage(), e1);
            throw new DriverImportFailedError();
        } catch (IllegalAccessException e1) {
            e1.printStackTrace();
            LOG.error("init : " + e1.getMessage(), e1);
            throw new DriverImportFailedError();
        } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
            LOG.error("init : " + e1.getMessage(), e1);
            throw new DriverImportFailedError();
        } catch (SQLException e) {
            e.printStackTrace();
            LOG.error("init : " + e.getMessage(), e);
            throw new CouldNotConnectToDBException();
        }
    }

    private boolean isClosed() {
        try {
            return this.conn == null || this.conn.isClosed();
        } catch (SQLException e) {
            LOG.error("isClosed : " + e.getMessage(), e);
            return true;
        }
    }
}
